#!/usr/bin/env python
from __future__ import print_function, unicode_literals
import sys

if __name__ == '__main__' and sys.version_info[0] < 3:
    print('Only Python 3 is supported, QUITTING!', file=sys.stderr)
    sys.exit(-1)


from jsython.main import main


if __name__ == '__main__':
    main(sys.argv)
